spring.config.import=optional:file:.env[.properties]
spring.application.name=internship
server.port=${BACKEND_PORT}

# Database Configuration
# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


minio.url=${MINIO_API_URL}
minio.access-key=${MINIO_USERNAME}
minio.secret-key=${MINIO_PASSWORD}
minio.bucket-name=${MINIO_PROJECT_NAME}

spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=${MAIL_PROTOCOL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

api.prefix=api/v1
file.storage.location=./minio/uploads